name: Test Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # 👉 agar bisa dijalankan manual

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "✅ Workflow jalan!"
